# Generated by Django 5.1.15 on 2026-08-24 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cidadaos', '0001_initial'),
        ('contas', '0001_initial'),
        ('institucional', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficioEventual',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('nome_da_pessoa', models.TextField(db_column='personName')),
                ('tipo', models.TextField(db_column='type')),
                ('tipo_outro', models.TextField(blank=True, db_column='typeOther', null=True)),
                ('descricao', models.TextField(blank=True, db_column='description', null=True)),
                ('criado_em', models.DateTimeField(db_column='createdAt')),
                ('atualizado_em', models.DateTimeField(db_column='updatedAt')),
                ('excluido_em', models.DateTimeField(blank=True, db_column='deletedAt', null=True)),
                ('cidadao', models.ForeignKey(db_column='citizenId', on_delete=django.db.models.deletion.DO_NOTHING, related_name='beneficios', to='cidadaos.cidadao')),
                ('registrado_por', models.ForeignKey(db_column='registeredById', on_delete=django.db.models.deletion.DO_NOTHING, related_name='beneficios_registrados', to='contas.operador')),
                ('unidade', models.ForeignKey(blank=True, db_column='unitId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='beneficios', to='institucional.unidade')),
            ],
            options={
                'verbose_name': 'benefício eventual',
                'verbose_name_plural': 'benefícios eventuais',
                'db_table': 'eventual_benefits',
                'ordering': ['-criado_em'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('protocolo', models.TextField(db_column='protocol')),
                ('situacao', models.TextField(db_column='status', default='EM_TRIAGEM')),
                ('prioridade', models.TextField(db_column='priority', default='NORMAL')),
                ('descricao', models.TextField(blank=True, db_column='description', null=True)),
                ('familia_id', models.TextField(blank=True, db_column='familyId', null=True)),
                ('demanda_id', models.TextField(db_column='demandId')),
                ('aberto_em', models.DateTimeField(db_column='openedAt')),
                ('fechado_em', models.DateTimeField(blank=True, db_column='closedAt', null=True)),
                ('ativo', models.BooleanField(db_column='isActive', default=True)),
                ('criado_em', models.DateTimeField(db_column='createdAt')),
                ('atualizado_em', models.DateTimeField(db_column='updatedAt')),
                ('excluido_em', models.DateTimeField(blank=True, db_column='deletedAt', null=True)),
                ('cidadao', models.ForeignKey(db_column='citizenId', on_delete=django.db.models.deletion.DO_NOTHING, related_name='casos', to='cidadaos.cidadao')),
                ('tecnico', models.ForeignKey(blank=True, db_column='technicianId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='casos_atribuidos', to='contas.operador')),
                ('unidade', models.ForeignKey(db_column='unitId', on_delete=django.db.models.deletion.DO_NOTHING, related_name='casos', to='institucional.unidade')),
            ],
            options={
                'verbose_name': 'caso',
                'verbose_name_plural': 'casos',
                'db_table': 'cases',
                'ordering': ['-aberto_em'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SenhaDaFila',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('senha', models.TextField(db_column='ticket')),
                ('prioridade', models.TextField(db_column='priority', default='NORMAL')),
                ('situacao', models.TextField(db_column='status', default='AGUARDANDO')),
                ('servico', models.TextField(blank=True, db_column='serviceName', null=True)),
                ('chamado_em', models.DateTimeField(blank=True, db_column='calledAt', null=True)),
                ('finalizado_em', models.DateTimeField(blank=True, db_column='finishedAt', null=True)),
                ('criado_em', models.DateTimeField(db_column='createdAt')),
                ('atualizado_em', models.DateTimeField(db_column='updatedAt')),
                ('atendido_por', models.ForeignKey(blank=True, db_column='attendedById', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='senhas_atendidas', to='contas.operador')),
                ('cidadao', models.ForeignKey(db_column='citizenId', on_delete=django.db.models.deletion.DO_NOTHING, related_name='senhas', to='cidadaos.cidadao')),
                ('unidade', models.ForeignKey(db_column='unitId', on_delete=django.db.models.deletion.DO_NOTHING, related_name='senhas', to='institucional.unidade')),
            ],
            options={
                'verbose_name': 'senha da fila',
                'verbose_name_plural': 'senhas da fila',
                'db_table': 'queue_tickets',
                'ordering': ['criado_em'],
                'managed': True,
            },
        ),
    ]
