# Generated by Django 5.1.15 on 2026-08-24 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0001_initial'),
        ('contas', '0001_initial'),
        ('institucional', '0001_initial'),
    ]

    operations = [
        # A tabela `itinerant_actions` ja existe: foi criada pelo esquema anterior.
        # `SeparateDatabaseAndState` registra o modelo no estado do Django sem
        # executar o CREATE TABLE — o contrario falharia, e recriar destruiria
        # as acoes ja cadastradas.
        migrations.SeparateDatabaseAndState(
            state_operations=[
        migrations.CreateModel(
            name='AcaoItinerante',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('titulo', models.TextField(db_column='title')),
                ('descricao', models.TextField(blank=True, db_column='description', null=True)),
                ('local', models.TextField(db_column='location')),
                ('data', models.DateTimeField(db_column='date')),
                ('observacoes', models.TextField(blank=True, db_column='observations', null=True)),
                ('participantes', models.IntegerField(db_column='attendees', default=0)),
                ('ativa', models.BooleanField(db_column='isActive', default=True)),
                ('criada_em', models.DateTimeField(db_column='createdAt')),
                ('atualizada_em', models.DateTimeField(db_column='updatedAt')),
                ('excluida_em', models.DateTimeField(blank=True, db_column='deletedAt', null=True)),
                ('responsavel', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.DO_NOTHING, related_name='acoes_itinerantes', to='contas.operador')),
                ('unidade', models.ForeignKey(db_column='unitId', on_delete=django.db.models.deletion.DO_NOTHING, related_name='acoes_itinerantes', to='institucional.unidade')),
            ],
            options={
                'verbose_name': 'ação itinerante',
                'verbose_name_plural': 'ações itinerantes',
                'db_table': 'itinerant_actions',
                'ordering': ['-data'],
                'managed': True,
            },
        )
            ],
            database_operations=[
                # `CREATE TABLE IF NOT EXISTS`, e nao CreateModel, porque esta tabela
                # existe no banco herdado mas precisa ser criada em bancos novos —
                # o de teste, e qualquer ambiente montado do zero. As duas
                # situacoes convivem sem passo manual de `--fake`.
                migrations.RunSQL(
                    """CREATE TABLE IF NOT EXISTS "itinerant_actions" (
                        "id" text NOT NULL PRIMARY KEY,
                        "title" text NOT NULL,
                        "description" text NULL,
                        "location" text NOT NULL,
                        "date" timestamp with time zone NOT NULL,
                        "observations" text NULL,
                        "attendees" integer NOT NULL DEFAULT 0,
                        "isActive" boolean NOT NULL DEFAULT true,
                        "createdAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        "updatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        "deletedAt" timestamp with time zone NULL,
                        "userId" text NOT NULL,
                        "unitId" text NOT NULL
                    );""",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        migrations.AddField(
            model_name='beneficioeventual',
            name='acao_itinerante',
            field=models.ForeignKey(blank=True, db_column='itinerantActionId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='beneficios', to='atendimentos.acaoitinerante'),
        ),
        migrations.AddField(
            model_name='caso',
            name='acao_itinerante',
            field=models.ForeignKey(blank=True, db_column='itinerantActionId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='casos', to='atendimentos.acaoitinerante'),
        ),
    ]
