# Generated by Django 5.1.15 on 2026-08-24 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0002_acaoitinerante_beneficioeventual_acao_itinerante_and_more'),
        ('cidadaos', '0002_cidadao_acao_itinerante'),
        ('contas', '0001_initial'),
        ('institucional', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtendimentoDeRecepcao',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('demanda', models.TextField(db_column='demand')),
                ('desfecho', models.TextField(db_column='outcome')),
                ('motivo', models.TextField(blank=True, db_column='reason', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('acao_itinerante', models.ForeignKey(blank=True, db_column='itinerantActionId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='atendimentos_de_recepcao', to='atendimentos.acaoitinerante')),
                ('atendido_por', models.ForeignKey(db_column='attendedById', on_delete=django.db.models.deletion.DO_NOTHING, related_name='atendimentos_de_recepcao', to='contas.operador')),
                ('caso', models.ForeignKey(blank=True, db_column='caseId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='atendimentos_de_recepcao', to='atendimentos.caso')),
                ('cidadao', models.ForeignKey(db_column='citizenId', on_delete=django.db.models.deletion.DO_NOTHING, related_name='atendimentos_de_recepcao', to='cidadaos.cidadao')),
                ('unidade', models.ForeignKey(db_column='unitId', on_delete=django.db.models.deletion.DO_NOTHING, related_name='atendimentos_de_recepcao', to='institucional.unidade')),
            ],
            options={
                'verbose_name': 'atendimento de recepção',
                'verbose_name_plural': 'atendimentos de recepção',
                'db_table': 'reception_visits',
                'ordering': ['-criado_em'],
                'managed': True,
                'indexes': [models.Index(fields=['cidadao', 'criado_em'], name='recepcao_cidadao_data_idx')],
            },
        ),
    ]
