# Generated by Django 5.1.15 on 2026-08-24 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0003_atendimentoderecepcao'),
        ('contas', '0001_initial'),
        ('institucional', '0002_demanda'),
    ]

    operations = [
        # `referrals` ja existe. O modelo entra no estado; a unica alteracao real
        # e a coluna de destino interno, aplicada em seguida.
        migrations.SeparateDatabaseAndState(
            state_operations=[
        migrations.CreateModel(
            name='Encaminhamento',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('destino_externo', models.TextField(db_column='targetEntity')),
                ('motivo', models.TextField(db_column='reason')),
                ('situacao', models.TextField(db_column='status', default='PENDENTE')),
                ('observacoes', models.TextField(blank=True, db_column='notes', null=True)),
                ('criado_em', models.DateTimeField(db_column='createdAt')),
                ('atualizado_em', models.DateTimeField(db_column='updatedAt')),
                ('caso', models.ForeignKey(db_column='caseId', on_delete=django.db.models.deletion.DO_NOTHING, related_name='encaminhamentos', to='atendimentos.caso')),
                ('encaminhado_por', models.ForeignKey(db_column='referredById', on_delete=django.db.models.deletion.DO_NOTHING, related_name='encaminhamentos_feitos', to='contas.operador')),
                ('unidade_destino', models.ForeignKey(blank=True, db_column='targetUnitId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='encaminhamentos_recebidos', to='institucional.unidade')),
            ],
            options={
                'verbose_name': 'encaminhamento',
                'verbose_name_plural': 'encaminhamentos',
                'db_table': 'referrals',
                'ordering': ['-criado_em'],
                'managed': True,
            },
        )
            ],
            database_operations=[
                # `CREATE TABLE IF NOT EXISTS`, e nao CreateModel, porque esta tabela
                # existe no banco herdado mas precisa ser criada em bancos novos —
                # o de teste, e qualquer ambiente montado do zero. As duas
                # situacoes convivem sem passo manual de `--fake`.
                migrations.RunSQL(
                    """CREATE TABLE IF NOT EXISTS "referrals" (
                        "id" text NOT NULL PRIMARY KEY,
                        "caseId" text NOT NULL,
                        "referredById" text NOT NULL,
                        "targetEntity" text NOT NULL,
                        "reason" text NOT NULL,
                        "status" text NOT NULL DEFAULT 'PENDENTE',
                        "notes" text NULL,
                        "createdAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        "updatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
                    );""",
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    'ALTER TABLE referrals ADD COLUMN IF NOT EXISTS "targetUnitId" text NULL '
                    'REFERENCES units(id) DEFERRABLE INITIALLY DEFERRED;',
                    reverse_sql='ALTER TABLE referrals DROP COLUMN IF EXISTS "targetUnitId";',
                ),
            ],
        ),
    ]
