# Generated by Django 5.1.15 on 2026-08-24 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0004_encaminhamento'),
        ('institucional', '0003_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='servico',
            field=models.ForeignKey(blank=True, db_column='serviceId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos', to='institucional.servico'),
        ),
        migrations.AlterField(
            model_name='caso',
            name='demanda_id',
            field=models.TextField(blank=True, db_column='demandId', null=True),
        ),
    ]
