# Generated by Django 5.1.15 on 2026-08-31 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0005_caso_servico_alter_caso_demanda_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='acaoitinerante',
            name='beneficios_concedidos',
            field=models.IntegerField(db_column='benefitsGranted', default=0),
        ),
        migrations.AddField(
            model_name='acaoitinerante',
            name='casos_abertos',
            field=models.IntegerField(db_column='casesOpened', default=0),
        ),
        migrations.AddField(
            model_name='acaoitinerante',
            name='cidadaos_atendidos',
            field=models.IntegerField(db_column='attendedCitizens', default=0),
        ),
        migrations.AddField(
            model_name='acaoitinerante',
            name='concluida',
            field=models.BooleanField(db_column='isCompleted', default=False),
        ),
    ]
