# Generated by Django 5.1.15 on 2026-09-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0006_acaoitinerante_beneficios_concedidos_and_more'),
        ('cidadaos', '0002_cidadao_acao_itinerante'),
        ('contas', '0001_initial'),
        ('institucional', '0003_servico'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='beneficioeventual',
            index=models.Index(fields=['-criado_em'], name='beneficio_criado_em_idx'),
        ),
        migrations.AddIndex(
            model_name='caso',
            index=models.Index(fields=['-aberto_em'], name='caso_aberto_em_idx'),
        ),
        migrations.AddIndex(
            model_name='caso',
            index=models.Index(fields=['unidade', 'situacao'], name='caso_unidade_situacao_idx'),
        ),
        migrations.AddIndex(
            model_name='caso',
            index=models.Index(fields=['-atualizado_em'], name='caso_atualizado_em_idx'),
        ),
        migrations.AddIndex(
            model_name='senhadafila',
            index=models.Index(fields=['unidade', 'situacao'], name='senha_unidade_situacao_idx'),
        ),
        migrations.AddIndex(
            model_name='senhadafila',
            index=models.Index(fields=['-criado_em'], name='senha_criado_em_idx'),
        ),
    ]
