# Generated by Django 5.1.15 on 2026-08-24 18:37

import apps.cidadaos.campos
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidadao',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('nome', models.TextField(db_column='name')),
                ('id_local', models.TextField(blank=True, db_column='localId', null=True, unique=True)),
                ('cpf', apps.cidadaos.campos.CampoCifrado(blank=True, db_column='cpfEncrypted', indice='cpfHash', null=True)),
                ('cpf_indice', models.TextField(blank=True, db_column='cpfHash', null=True, unique=True)),
                ('nis', apps.cidadaos.campos.CampoCifrado(blank=True, db_column='nisEncrypted', indice='nisHash', null=True)),
                ('nis_indice', models.TextField(blank=True, db_column='nisHash', null=True)),
                ('email', apps.cidadaos.campos.CampoCifrado(blank=True, db_column='emailEncrypted', indice='emailHash', null=True)),
                ('email_indice', models.TextField(blank=True, db_column='emailHash', null=True, unique=True)),
                ('rg', apps.cidadaos.campos.CampoCifrado(blank=True, db_column='rgEncrypted', null=True)),
                ('telefone', apps.cidadaos.campos.CampoCifrado(blank=True, db_column='phoneEncrypted', null=True)),
                ('endereco', apps.cidadaos.campos.CampoCifrado(blank=True, db_column='addressEncrypted', null=True)),
                ('nascimento', models.DateTimeField(blank=True, db_column='birthDate', null=True)),
                ('sexo', models.TextField(blank=True, db_column='gender', null=True)),
                ('naturalidade', models.TextField(blank=True, db_column='naturality', null=True)),
                ('escolaridade', models.TextField(blank=True, db_column='education', null=True)),
                ('identidade_de_genero', models.TextField(blank=True, db_column='genderIdentity', null=True)),
                ('raca', models.TextField(blank=True, db_column='race', null=True)),
                ('tem_deficiencia', models.BooleanField(blank=True, db_column='hasDisability', null=True)),
                ('estado_civil', models.TextField(blank=True, db_column='maritalStatus', null=True)),
                ('bairro', models.TextField(blank=True, db_column='neighborhood', null=True)),
                ('cidade', models.TextField(blank=True, db_column='city', null=True)),
                ('uf', models.TextField(blank=True, db_column='state', null=True)),
                ('cep', models.TextField(blank=True, db_column='zipCode', null=True)),
                ('observacoes', models.TextField(blank=True, db_column='notes', null=True)),
                ('documentos', models.JSONField(blank=True, db_column='documentData', null=True)),
                ('endereco_detalhado', models.JSONField(blank=True, db_column='addressData', null=True)),
                ('socioeconomico', models.JSONField(blank=True, db_column='socioeconomicData', null=True)),
                ('ingresso', models.JSONField(blank=True, db_column='entryData', null=True)),
                ('membros_da_familia', models.JSONField(blank=True, db_column='familyMembers', null=True)),
                ('termo_de_responsabilidade', models.JSONField(blank=True, db_column='responsibilityTerm', null=True)),
                ('anexos', models.JSONField(blank=True, db_column='attachedDocuments', null=True)),
                ('autoriza_imagem', models.BooleanField(blank=True, db_column='imageAuthorization', null=True)),
                ('imagem_aceita_em', models.DateTimeField(blank=True, db_column='imageAuthorizationAcceptedAt', null=True)),
                ('imagem_responsavel', models.TextField(blank=True, db_column='imageAuthorizationResponsible', null=True)),
                ('imagem_revogada_em', models.DateTimeField(blank=True, db_column='imageAuthorizationRevokedAt', null=True)),
                ('consentiu_tefe_cidadao_em', models.DateTimeField(blank=True, db_column='tefeCidadaoConsentAt', null=True)),
                ('situacao_beneficiario', models.TextField(blank=True, db_column='beneficiarySituation', null=True)),
                ('atualizado_por', models.TextField(blank=True, db_column='updatedByName', null=True)),
                ('sincronizado', models.BooleanField(db_column='synchronized', default=True)),
                ('situacao_sincronizacao', models.TextField(blank=True, db_column='syncStatus', null=True)),
                ('familia_id', models.TextField(blank=True, db_column='familyId', null=True)),
                ('ativo', models.BooleanField(db_column='isActive', default=True)),
                ('criado_em', models.DateTimeField(db_column='createdAt')),
                ('atualizado_em', models.DateTimeField(db_column='updatedAt')),
                ('excluido_em', models.DateTimeField(blank=True, db_column='deletedAt', null=True)),
            ],
            options={
                'verbose_name': 'cidadão',
                'verbose_name_plural': 'cidadãos',
                'db_table': 'citizens',
                'ordering': ['nome'],
                'managed': True,
            },
        ),
    ]
