# Generated by Django 5.1.15 on 2026-08-24 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0002_acaoitinerante_beneficioeventual_acao_itinerante_and_more'),
        ('cidadaos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidadao',
            name='acao_itinerante',
            field=models.ForeignKey(blank=True, db_column='itinerantActionId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cidadaos', to='atendimentos.acaoitinerante'),
        ),
    ]
