# Generated by Django 5.1.15 on 2026-09-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0007_beneficioeventual_beneficio_criado_em_idx_and_more'),
        ('cidadaos', '0002_cidadao_acao_itinerante'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cidadao',
            index=models.Index(fields=['-atualizado_em'], name='cidadao_atualizado_em_idx'),
        ),
    ]
