# Generated by Django 5.1.15 on 2026-08-24 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institucional', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('email', models.TextField(unique=True)),
                ('nome', models.TextField(db_column='name')),
                ('cpf', models.TextField(blank=True, null=True)),
                ('papel', models.TextField(db_column='role')),
                ('ativo', models.BooleanField(db_column='isActive', default=True)),
                ('keycloak_id', models.TextField(blank=True, db_column='keycloakId', null=True)),
                ('criado_em', models.DateTimeField(db_column='createdAt')),
                ('atualizado_em', models.DateTimeField(db_column='updatedAt')),
                ('excluido_em', models.DateTimeField(blank=True, db_column='deletedAt', null=True)),
                ('unidade', models.ForeignKey(blank=True, db_column='unitId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='operadores', to='institucional.unidade')),
            ],
            options={
                'verbose_name': 'operador',
                'verbose_name_plural': 'operadores',
                'db_table': 'users',
                'ordering': ['nome'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PedidoDeAcesso',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('keycloak_id', models.TextField(db_column='keycloakId')),
                ('email', models.TextField()),
                ('nome', models.TextField(db_column='name')),
                ('situacao', models.TextField(db_column='status', default='PENDENTE')),
                ('pedido_em', models.DateTimeField(db_column='requestedAt')),
                ('decidido_em', models.DateTimeField(blank=True, db_column='decidedAt', null=True)),
                ('papel_concedido', models.TextField(blank=True, db_column='grantedRole', null=True)),
                ('unidade_concedida', models.TextField(blank=True, db_column='grantedUnitId', null=True)),
                ('decidido_por', models.ForeignKey(blank=True, db_column='decidedById', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='decisoes_de_acesso', to='contas.operador')),
            ],
            options={
                'verbose_name': 'pedido de acesso',
                'verbose_name_plural': 'pedidos de acesso',
                'db_table': 'access_requests',
                'ordering': ['pedido_em'],
                'managed': True,
            },
        ),
    ]
