# Generated by Django 5.1.15 on 2026-08-24 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordenacao',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('nome', models.TextField(db_column='name')),
                ('sigla', models.TextField(db_column='code', unique=True)),
                ('ativa', models.BooleanField(db_column='isActive', default=True)),
                ('criada_em', models.DateTimeField(db_column='createdAt')),
                ('atualizada_em', models.DateTimeField(db_column='updatedAt')),
                ('excluida_em', models.DateTimeField(blank=True, db_column='deletedAt', null=True)),
                ('superior', models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subordinadas', to='institucional.coordenacao')),
            ],
            options={
                'verbose_name': 'coordenação',
                'verbose_name_plural': 'coordenações',
                'db_table': 'coordinations',
                'ordering': ['nome'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('nome', models.TextField(db_column='name')),
                ('sigla', models.TextField(db_column='code', unique=True)),
                ('tipo', models.TextField(db_column='type')),
                ('endereco', models.TextField(blank=True, db_column='address', null=True)),
                ('telefone', models.TextField(blank=True, db_column='phone', null=True)),
                ('ativa', models.BooleanField(db_column='isActive', default=True)),
                ('criada_em', models.DateTimeField(db_column='createdAt')),
                ('atualizada_em', models.DateTimeField(db_column='updatedAt')),
                ('excluida_em', models.DateTimeField(blank=True, db_column='deletedAt', null=True)),
                ('coordenacao', models.ForeignKey(blank=True, db_column='coordinationId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='unidades', to='institucional.coordenacao')),
            ],
            options={
                'verbose_name': 'unidade',
                'verbose_name_plural': 'unidades',
                'db_table': 'units',
                'ordering': ['nome'],
                'managed': True,
            },
        ),
    ]
