# Generated by Django 5.1.15 on 2026-08-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0001_initial'),
    ]

    operations = [
        # A tabela `demands` ja existe no esquema herdado. Registra o modelo no
        # estado do Django sem executar o CREATE TABLE.
        migrations.SeparateDatabaseAndState(
            state_operations=[
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('nome', models.TextField(db_column='name')),
                ('descricao', models.TextField(blank=True, db_column='description', null=True)),
                ('categoria', models.TextField(blank=True, db_column='category', null=True)),
                ('ativa', models.BooleanField(db_column='isActive', default=True)),
                ('criada_em', models.DateTimeField(db_column='createdAt')),
                ('atualizada_em', models.DateTimeField(db_column='updatedAt')),
            ],
            options={
                'verbose_name': 'demanda',
                'verbose_name_plural': 'demandas',
                'db_table': 'demands',
                'ordering': ['nome'],
                'managed': True,
            },
        )
            ],
            database_operations=[
                # `CREATE TABLE IF NOT EXISTS`, e nao CreateModel, porque esta tabela
                # existe no banco herdado mas precisa ser criada em bancos novos —
                # o de teste, e qualquer ambiente montado do zero. As duas
                # situacoes convivem sem passo manual de `--fake`.
                migrations.RunSQL(
                    """CREATE TABLE IF NOT EXISTS "demands" (
                        "id" text NOT NULL PRIMARY KEY,
                        "name" text NOT NULL,
                        "description" text NULL,
                        "category" text NULL,
                        "isActive" boolean NOT NULL DEFAULT true,
                        "createdAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        "updatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
                    );""",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
    ]
