# Generated by Django 5.1.15 on 2026-08-24 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0002_demanda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('nome', models.TextField(db_column='name')),
                ('descricao', models.TextField(blank=True, db_column='description', null=True)),
                ('ativo', models.BooleanField(db_column='isActive', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('demanda', models.ForeignKey(blank=True, db_column='demandId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicos', to='institucional.demanda')),
                ('unidade', models.ForeignKey(db_column='unitId', on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='institucional.unidade')),
            ],
            options={
                'verbose_name': 'serviço',
                'verbose_name_plural': 'serviços',
                'db_table': 'unit_services',
                'ordering': ['unidade__nome', 'nome'],
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('unidade', 'nome'), name='servico_unico_por_unidade')],
            },
        ),
    ]
