# Generated by Django 5.1.15 on 2026-08-24 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroDeAuditoria',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('acao', models.TextField(db_column='action')),
                ('entidade', models.TextField(db_column='entity')),
                ('entidade_id', models.TextField(blank=True, db_column='entityId', null=True)),
                ('dados_antes', models.JSONField(blank=True, db_column='oldData', null=True)),
                ('dados_depois', models.JSONField(blank=True, db_column='newData', null=True)),
                ('endereco_ip', models.TextField(blank=True, db_column='ipAddress', null=True)),
                ('navegador', models.TextField(blank=True, db_column='userAgent', null=True)),
                ('criado_em', models.DateTimeField(db_column='createdAt')),
                ('operador', models.ForeignKey(blank=True, db_column='userId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='registros_de_auditoria', to='contas.operador')),
            ],
            options={
                'verbose_name': 'registro de auditoria',
                'verbose_name_plural': 'registros de auditoria',
                'db_table': 'audit_logs',
                'ordering': ['-criado_em'],
                'managed': True,
            },
        ),
    ]
