# Generated by Django 5.1.15 on 2026-09-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='registrodeauditoria',
            index=models.Index(fields=['-criado_em'], name='auditoria_criado_em_idx'),
        ),
        migrations.AddIndex(
            model_name='registrodeauditoria',
            index=models.Index(fields=['entidade', 'entidade_id'], name='auditoria_entidade_idx'),
        ),
    ]
